language: ruby

cache: bundler

rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5

before_install:
  - gem update --system
  # Stay on Bundler 1.x (for dependency reasons as we want to support Rails 4.2.x and Ruby 2.3.x)
  # More info here: https://docs.travis-ci.com/user/languages/ruby/#bundler-20
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_rc1.gemfile

matrix:
  exclude:
    - gemfile: gemfiles/rails_6_rc1.gemfile
      rvm: 2.3.8
    - gemfile: gemfiles/rails_6_rc1.gemfile
      rvm: 2.4.6
